name: CURRENTFORM
favicon: null
layout_spectrum: 0.04247145773842931
typography_spectrum: 0.06761960661970079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4803331773728132
  lightness: 0.1149120987392962
  saturation: 0.6775362661574036
  rhythmicContrast: 0.6475573135539889
purpose: []
