name: CURRENTFORM
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#0000ff'
    - '#000000'
    - '#240000'
    - '#141414'
  brandStrength: 0.4803331773728132
  lightness: 1
  saturation: 0.6775362661574036
  rhythmicContrast: 0.6475573135539889
purpose: []
